backend:
  name: test-repo
media_folder: static/assets
public_folder: assets
collections:
  - name: works
    label: Work
    folder: work
    create: true
    fields:
      - { name: path, label: Path }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
